### PR TITLE
Handle multiple occurrence of subfields

### LINKED ISSUE #11: __get_subfield_text(self, marc_field, index) should return a List of string
- use `get_subfields` in Marc21
- map over elements in XML and return their text nodes
- rename to `get_subfield_texts`
- adapt tests
- add tests case for 000059794 for Marc21 and XML (MarcXML and AlephX)

### PR DESCRIPTION
**Pull request by tobiasschweizer**
resolves #11

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@BalduinLandolt It would be nice to have the MarcXML file, too.

**Comment by BalduinLandolt** [comment]
I added Sample Data (both AlephX and Marc21) for tests for four more letters:
- 000307927
- 000056870
- 000054774
- 000059552

With that, we have everything covered in our tests, except:
- 751, Subfield 'g'
- 046, Subfield 'e'
- 300, Subfields 'b' and 'e'
I guess we can live with that, right?

MarcXML files should follow soon.

**Comment by tobiasschweizer** [comment]
@BalduinLandolt Could you add the test `test_recipient_with_multiple_roles` for MarcXML?

Then we can go on add more test cases in all implementations.

**Comment by BalduinLandolt** [comment]
> 
> 
> @BalduinLandolt Could you add the test `test_recipient_with_multiple_roles` for MarcXML?
> 
> Then we can go on add more test cases in all implementations.

Timewise, probably not before tomorrow afternoon.

**Comment by BalduinLandolt** [comment]
Oh... I realize now... this has been waiting for my review all along, right? ^^

**Comment by tobiasschweizer** [comment]
@BalduinLandolt Could you create subfolders in  `sample_data` for Marc21, MarcXML, and AlephX files and adapt the path in the tests? Thanks you!

**Comment by tobiasschweizer** [comment]
@BalduinLandolt Thanks a lot!

**Pull request merged**
